---
apiVersion: v1
kind: Namespace
metadata:
  name: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
  labels:
    app.kubernetes.io/instance: website
    app.kubernetes.io/name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: website
      app.kubernetes.io/name: website
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: website
        app.kubernetes.io/name: website
    spec:
      securityContext:
        runAsUser: 101
      containers:
      - name: website
        image: ghcr.io/mbovo/website:v0.1.10
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: website
  labels:
    app.kubernetes.io/instance: website
    app.kubernetes.io/name: website
spec:
  selector:
    app.kubernetes.io/instance: website
    app.kubernetes.io/name: website
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: http

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: website
  namespace: website
  labels:
    app.kubernetes.io/instance: website
    app.kubernetes.io/name: website
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
