FROM nginx:stable-alpine
COPY public /usr/share/nginx/html

LABEL org.opencontainers.image.version=v1.0.0
LABEL org.opencontainers.image.title=website
LABEL org.opencontainers.image.description="Manuel's website"
LABEL org.opencontainers.image.vendor="Manuel Bovo"
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.source="https://github.com/mbovo/website"

EXPOSE 80