name: "Tag and build"
on:
  push:
    tags: ["*"]
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    name: "Build & Push wheel"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v3
        with:
          version: latest
          extended: false
          args: --cleanDestinationDir --minify --verbose
      - name: Release
        uses: softprops/action-gh-release@v1
        with:  
          generate_release_notes: true
          files: |
            public/*
            LICENSE

  docker-build:
    name: "Build docker image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v3
        with:
          version: latest
          extended: false
          args: --cleanDestinationDir --minify --verbose --destination containers/nginx/public

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{env.IMAGE_NAME}}
          flavor: |
            latest=auto
            prefix=
            suffix=
          tags: |
            type=raw,value=${{github.ref_name}}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: containers/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
